"""Validate actual Intel XPU RMVPE and HuBERT feature extraction.

Produces only synthetic audio in a uniquely named temporary experiment.
No GPU -> fails closed. Doesn't touch other users' checkpoints or datasets.
"""
import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile
import time

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np
import torch

from rvc.configs.config import require_xpu
from rvc.train.extract.storage import valid_npy
from scripts.xpu_one_epoch import make_dataset


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--keep", action="store_true", help="Keep generated files after success")
    parser.add_argument("--download", action="store_true", help="Download prerequisite RMVPE and HuBERT models if missing")
    parser.add_argument("--sample-rate", type=int, choices=(24000, 32000, 40000, 48000), default=40000)
    args = parser.parse_args()

    require_xpu()
    predictor = ROOT / "rvc/models/predictors/rmvpe.pt"
    embedder = ROOT / "rvc/models/embedders/contentvec/pytorch_model.bin"
    if (not predictor.exists() or not embedder.exists()) and args.download:
        from rvc.lib.tools.prerequisites_download import prequisites_download_pipeline
        print("[PREREQUISITES] Downloading upstream Applio RMVPE/ContentVec models...", flush=True)
        prequisites_download_pipeline(pretraineds_hifigan=False, models=True, exe=False)
    missing = [str(x) for x in (predictor, embedder) if not x.is_file()]
    if missing:
        raise RuntimeError(
            "Pretrained F0/HuBERT assets are missing: " + ", ".join(missing)
            + ". Launch Applio once to download prerequisites, or rerun this test with --download."
        )

    logs = ROOT / "logs"
    logs.mkdir(exist_ok=True)
    exp = pathlib.Path(tempfile.mkdtemp(prefix="__xpu_feature_", dir=logs))
    try:
        make_dataset(exp, sample_rate=args.sample_rate)
        # Force fresh *actual* GPU extraction; do not accept the synthetic
        # label data generated by make_dataset as proof of XPU extraction.
        for folder in ("f0", "f0_voiced", "extracted"):
            for cache in (exp / folder).glob("*.npy"):
                cache.unlink()
        cmd = [
            sys.executable, str(ROOT / "rvc/train/extract/extract.py"),
            str(exp), "rmvpe", "1", "0", str(args.sample_rate),
            "contentvec", "None", "0",
        ]
        print("[EXTRACT] Testing real RMVPE and HuBERT on Intel XPU", flush=True)
        start = time.perf_counter()
        finished = subprocess.run(cmd, cwd=ROOT, check=False)
        if finished.returncode != 0:
            raise RuntimeError(
                f"Feature extraction returned exit code {finished.returncode}. "
                "See the first traceback above."
            )

        n = 0
        for wav in (exp / "sliced_audios").glob("*.wav"):
            stem = wav.name
            candidates = (
                (exp / "f0" / f"{stem}.npy", 1),
                (exp / "f0_voiced" / f"{stem}.npy", 1),
                (exp / "extracted" / f"{wav.stem}.npy", 2),
            )
            if not all(valid_npy(path, rank) for path, rank in candidates):
                raise RuntimeError(f"Real Intel XPU extraction failed to produce valid labels for {stem}")
            n += 1
        if n != 8 or not (exp / "filelist.txt").is_file():
            raise RuntimeError(f"Expected 8 fully extracted clips and a training filelist; found {n}")
        print(
            f"[PASS] Real XPU RMVPE+HuBERT extraction and filelist on {n} clips "
            f"({args.sample_rate} Hz) in {time.perf_counter()-start:.1f}s",
            flush=True,
        )
    except BaseException:
        print(f"[PRESERVED] Feature-extraction diagnostic folder: {exp}", flush=True)
        raise
    else:
        if args.keep:
            print(f"[KEPT] Diagnostic experiment and features: {exp}")
        else:
            shutil.rmtree(exp)
            print("[CLEAN] Temporary synthetic feature-test folder removed")


if __name__ == "__main__":
    main()
